### ISSUE TITLE
Use Rubocop for consistent style?

### ISSUE THREAD

**Issue by tminor** [borusg/noodle#24]
Hi!

Feel free to call me names and close this if you hate the idea, but how would you feel about using Rubocop for linting? I've been using if for quite a while and it helps me sleep more soundly at night and also gives some great advice!

On a related note, would you be horribly offended if I began linting according to my `.rubocop.yml`?

**Comment by happymcplaksin** [comment]
Great idea! Feel free! Thank you!

Doing this is always on my mental list somewhere but I guess I never made a separate Issue for it.
