### ISSUE TITLE
Different analyzer to split fqdn

### ISSUE THREAD

**Issue by gungazoo** [borusg/noodle#29]
If you want to use a standard analyzer to split fqdn on '.' I think you can use the standard analyzer for that:

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-simple-analyzer.html

**Comment by happymcplaksin** [comment]
Would this be a win over how it's set up now? (Honest question!)

**Comment by gungazoo** [comment]
Only upside I see is that somebody else maintains it and as ES changes the simple analyzer (accidentally said standard above) would automatically change with it.  Other than that I see no benefit.

**Comment by happymcplaksin** [comment]
WRT who maintains, my understanding is that [Noodle currently](https://github.com/borusg/noodle/blob/master/lib/noodle/repository.rb#L18-L43) is using a built-in analyzer and tokenizer

But maybe I'm missing your point?

**Comment by gungazoo** [comment]
I think  we could use the simple analyzer for just the fqdn field.  I'm happy with the way it is.  Just offering it up.

**Comment by mitchellen** [comment]
Late to the party, but can this be closed?

**Comment by happymcplaksin** [comment]
Yes, at some point we [worked out a solution](https://github.com/borusg/noodle/blob/main/lib/noodle/repository.rb#L22-L37)
