### ISSUE TITLE
Add ability to configure noodle via YAML, JSON, or some other configuration file format

### ISSUE THREAD

**Issue by tminor** [borusg/noodle#31]
All the cool kids are using YAML, but I think YAML's readability is one of its clearest benefits. Does anyone have differing opinions or otherwise strongly oppose YAML or strongly favor something else?

**Comment by happymcplaksin** [comment]
You're thinking of config beyond config.ru? Or just something easier/different from config.ru?

**Comment by tminor** [comment]
Definitely something more generic. I did some searching and found a wide variety of usage patterns, some of which included `config.ru` and some other configuration file. I'd personally prefer to see noodle-specific configuration outside of `config.ru`. I think `ilk-equals-option` serves as a good example of what I consider noodle-specific configuration. Stuff like this:

```
bin/noodlin param limits.gum=hash                                   default.option.example.com
bin/noodlin param limits.role=array                                 default.option.example.com
bin/noodlin param limits.components=array                           default.option.example.com
bin/noodlin param limits.component_instances=array                  default.option.example.com
bin/noodlin param limits.listen_ports=array                         default.option.example.com
bin/noodlin param limits.destinations=array                         default.option.example.com
bin/noodlin param limits.stack=array                                default.option.example.com
bin/noodlin param limits.bareword_terms=array                       default.option.example.com
bin/noodlin param limits.uniqueness_params=array                    default.option.example.com
bin/noodlin param limits.required_params=array                      default.option.example.com
bin/noodlin param limits.ilk=array                                  default.option.example.com

bin/noodlin optionrefresh

bin/noodlin param uniqueness_params=ilk                             default.option.example.com
bin/noodlin param required_params=ilk,prodlevel,project,site,status default.option.example.com
bin/noodlin param bareword_terms=prodlevel,project,site             default.option.example.com
bin/noodlin param default_status=enabled                            default.option.example.com
bin/noodlin param default_ilk=host                                  default.option.example.com
bin/noodlin param limits.ilk=foo,bar,baz                            default.option.example.com

bin/noodlin param limits.prodlevel=dev,preprod,prod,test            default.option.example.com
bin/noodlin param limits.status=disabled,enabled,future,surplus     default.option.example.com

bin/noodlin optionrefresh
```

**Comment by happymcplaksin** [comment]
This doesn't eliminate the need for a config file, but for what it's worth the idea with `ilk=option` is that those options live in Noodle itself. You can use `noodlin` to add/change those options on the fly without having to reload the Noodle service.

Options about the service itself could live in a config file. Like log file and debug level, the name of the Noodle index in Elasticsearch, etc.

**Comment by tminor** [comment]
That makes sense! Being simple minded, my expectation is that configuration changes are generally made in a configuration file of some sort. If documented appropriately, I think the intended approach is fine!
